### ISSUE TITLE
Traceback for @anica

### ISSUE THREAD

**Issue by AlManja** [CristiVlad25/steem-desktop#1]
This user has no 'main' blog posts, just few comments, maybe this is the culprit?

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/al/py_36/7_steem/steem_desktop1/steem_desktop.pyw", line 60, in callback
    post = piston.post.Post(acnt.steem.get_blog(entry1.get())[0])
IndexError: list index out of range

**Comment by CristiVlad25** [comment]
The purpose for which I've started this mini project is for actual steemians to use mostly on their own profiles. And this assumes they're actively engaged with the steemit community, which is why there's little reason to focus on such an issue that would involve an inactive user, a bot, or any other type of account which does not imply higher level of activity (at least one post).

There are many errors that could spring for the basic code, because it's not optimized and/or secured. It mostly serves clear purposes and specific instructions. 

Thanks for pointing this out, and this specific issue could be resolved with 1-2 lines of additional code (conditional statement). 

Thanks for your engagement and I'm looking forward to hearing more ideas/issues that you can address for this project. You can message me for further discussions!
